### ISSUE TITLE
Does not build on mac

### ISSUE THREAD

**Issue by lexansoft** [ethereum/ethash#49]
NDUSERCA312:ethash alexn$ make
./test/test.sh

################# Testing JS ##################
Ethash startup took: 204ms
Ethash cache hash: 3e660a3d5e20b957171a697b5a4035bdfbf6d18168dd1438dc6fec12c37e1ecb
Light client hashes averaged: 20ms
Hash = 9e737d37884a1be1862c4b80e97374ba3e75555e1cc2840b20708541c7bdbeb3

################# Testing C ##################
Scanning dependencies of target ethash
[ 20%] Building C object src/libethash/CMakeFiles/ethash.dir/io.c.o
[ 40%] Building C object src/libethash/CMakeFiles/ethash.dir/internal.c.o
In file included from /Users/alexn/projects/ethash/src/libethash/internal.c:38:
/Users/alexn/projects/ethash/src/libethash/sha3_cryptopp.h:12:28: warning: redefinition of typedef 'ethash_h256_t' is a C11 feature [-Wtypedef-redefinition]
typedef struct ethash_h256 ethash_h256_t;
                           ^
/Users/alexn/projects/ethash/src/libethash/ethash.h:54:47: note: previous definition is here
typedef struct ethash_h256 { uint8_t b[32]; } ethash_h256_t;
                                              ^
1 warning generated.
[ 60%] Building C object src/libethash/CMakeFiles/ethash.dir/io_posix.c.o
[ 80%] Building CXX object src/libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
Linking CXX static library libethash.a
[ 80%] Built target ethash
Scanning dependencies of target Test
[100%] Building CXX object test/c/CMakeFiles/Test.dir/test.cpp.o
Linking CXX executable Test
Undefined symbols for architecture x86_64:
  "boost::unit_test::unit_test_main(bool (*)(), int, char**)", referenced from:
      _main in test.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [test/c/Test] Error 1
make[3]: *** [test/c/CMakeFiles/Test.dir/all] Error 2
make[2]: *** [test/c/CMakeFiles/Test.dir/rule] Error 2
make[1]: *** [Test] Error 2
make: *** [test] Error 2
NDUSERCA312:ethash alexn$

**Comment by LefterisJP** [comment]
We have not compiled ethash with clang and this is why you get this output with clang. Is there any possibility you can use gcc in MacOsX?

The warning is due to missing some flag for Clang I suppose but the boost one is strange. Let me investigate.

**Comment by LefterisJP** [comment]
Should be fixed with: https://github.com/ethereum/ethash/pull/50
