### ISSUE TITLE
Try to provide better error messages when user's machine is out of memory

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/ethash#56]
Memory mapped file will not gracefully provide an error if the user's machine runs out of memory. It will cause a BUS error.

See https://github.com/ethereum/cpp-ethereum/issues/806#issuecomment-101988058

**Comment by fjl** [comment]
This should be extended to also handle cases where there is not enough disk space.

**Comment by LefterisJP** [comment]
This is what this PR: https://github.com/ethereum/ethash/pull/57 tries to do.

It's not returning error codes since we assume that all of these cases are fatal and really bad. There is only one error code. Null pointer for failure. But now there is at least a string printed with a critical error message in each failing case.

The string could somehow be written in a buffer and returned so that each implementation can choose how to show it to the user but that would require an API change.
