### ISSUE TITLE
Hash Rate Error in ethash_opencl.go

### ISSUE THREAD

**Issue by dlehenky** [ethereum/ethash#77]
Based on the ethminer-cpp code, Line 506 is not quite right. Rather than (loops \* 1000 \* 256), it should be (loops \* globalWorkSize). Note that globalWorkSize is the product of the --cl-global-work MULTIPLIER and --cl-local-work command line options to ethminer-cpp. The respective defaults are 4096 and 64, so the default value of m_globalWorkSize (in "ethminer") is 262144. The current GO code is close :) for the default values, but does not take into account that they are changeable at runtime (although I didn't look to see if that's the case in the GO implementation). For the cpp reference code see:
libethash-cl/ethash-cl-miner.cpp line 547 hook.searched(), which is defined in:
libethcore/EthashGPUMiner.cpp line 82 virtual bool searched()

HTH

-David

**Comment by fjl** [comment]
OpenCL support has been removed from the Go binding.
