### ISSUE TITLE
Unable to go get this package

### ISSUE THREAD

**Issue by congnt171** [ethereum/ethash#94]
go get github.com/ethereum/ethash

And get error

package github.com/ethereum/go-ethereum/pow: cannot find package "github.com/ethereum/go-ethereum/pow" in any of:
	/usr/lib/go-1.6/src/github.com/ethereum/go-ethereum/pow (from $GOROOT)
	/root/go/src/github.com/ethereum/go-ethereum/pow (from $GOPATH)

**Comment by sammy007** [comment]
Can we finally sort out compatibility issues? Maybe it worth tagging version and publishing it gopkg.in so side projects like open pool can rely on it?

**Comment by sammy007** [comment]
https://github.com/ethereum/ethash/pull/93

**Comment by mikeyb** [comment]
`go get github.com/ethereumproject/ethash`
`go get github.com/ethereumproject/go-ethereum/pow`
etc..

Should work for you long term as classic chain will stay PoW/ethash for the foreseeable future.

**Comment by karalabe** [comment]
https://godoc.org/github.com/ethereum/go-ethereum/consensus/ethash

We've switched over to our Go implementation of ethash. I doubt we'll be maintaining this library any longer.

**Comment by sammy007** [comment]
Okay, I am out from maintaining pool also. Cheers.

**Comment by karalabe** [comment]
Feel free to rage quit, but the proper way to depend on an external project in the Go world is to vendor it into your own repository. I am really sorry if we broke your code, it was not our intention. That is why I sent the link to the new implementation. I'd gladly help with integrating it.

**Comment by karalabe** [comment]
https://github.com/ethereum/ethash/pull/95 This should fix it for now all all eternity.

**Comment by karalabe** [comment]
This should be fixed now. Tried it and go get works for me. I've vendored in all go-ethereum dependencies so it should not break any time from now on. Please note however that a better one is available from the go-ethereum repository and it's highly recommended to use that since that will be the one receiving updates from now on.
